fernetKey: Z25WaFZ2VFg3dlp4V1g5ejE3TXJTSkF3VGtFcVN2TTU=
webserverSecretKey: Z25WaFZ2VFg3dlp4V1g5ejE3TXJTSkF3VGtFcVN2TTU=
executor: "KubernetesExecutor"

dags:
  gitSync:
    enabled: true
    repo: https://github.com/cynjof/kubernetes-airflow-spark
    branch: main
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"